# Generated by Django 2.2.5 on 2019-10-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regular',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regular',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilian',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilian',
            name='small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Order')),
            ],
        ),
    ]
