# Generated by Django 2.2.5 on 2019-10-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191004_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='payment',
            field=models.CharField(default='N', max_length=2),
            preserve_default=False,
        ),
    ]
